sudo: required
services:
  - docker

before_install:
  - docker build -t me/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true me/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "lrn-docker-react"
  env: "Lrn-docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-567504720652"
  bucket_path: "lrn-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"